artifacts_root : artifacts 

data_ingestion : 
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/campusx-official/100-days-of-deep-learning/main/day3/placement.csv
  local_data_file: artifacts/data_ingestion/placement.csv